/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToe;

import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Random;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rats
 */
public class TicTacToeBoard extends JFrame {

    /**
     * Creates new form TicTacToe GUI
     */
    public TicTacToeBoard () {
        
        super("TicTacToe");
        initComponents();
        initBoardAreas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XObuttonGroup = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        boardXOpanel = new javax.swing.JPanel();
        area9 = new javax.swing.JLabel();
        area8 = new javax.swing.JLabel();
        area6 = new javax.swing.JLabel();
        area5 = new javax.swing.JLabel();
        area1 = new javax.swing.JLabel();
        area3 = new javax.swing.JLabel();
        area2 = new javax.swing.JLabel();
        area7 = new javax.swing.JLabel();
        area4 = new javax.swing.JLabel();
        OrButton = new javax.swing.JRadioButton();
        XrButton = new javax.swing.JRadioButton();
        newGameButton = new javax.swing.JButton();
        chooseRButtonLabel = new javax.swing.JLabel();

        XObuttonGroup.add(OrButton);
        XObuttonGroup.add(XrButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        area9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area9.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area9.setPreferredSize(new java.awt.Dimension(180, 180));
        area9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area9MouseClicked(evt);
            }
        });

        area8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area8.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area8.setPreferredSize(new java.awt.Dimension(180, 180));
        area8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area8MouseClicked(evt);
            }
        });

        area6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area6.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area6.setPreferredSize(new java.awt.Dimension(180, 180));
        area6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area6MouseClicked(evt);
            }
        });

        area5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area5.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area5.setPreferredSize(new java.awt.Dimension(180, 180));
        area5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area5MouseClicked(evt);
            }
        });

        area1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area1.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area1.setPreferredSize(new java.awt.Dimension(180, 180));
        area1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area1MouseClicked(evt);
            }
        });

        area3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area3.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area3.setPreferredSize(new java.awt.Dimension(180, 180));
        area3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area3MouseClicked(evt);
            }
        });

        area2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area2.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area2.setPreferredSize(new java.awt.Dimension(180, 180));
        area2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area2MouseClicked(evt);
            }
        });

        area7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area7.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area7.setPreferredSize(new java.awt.Dimension(180, 180));
        area7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area7MouseClicked(evt);
            }
        });

        area4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/puste.png"))); // NOI18N
        area4.setToolTipText("Wciśnij podwójnym przyciskiem myszy");
        area4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area4.setPreferredSize(new java.awt.Dimension(180, 180));
        area4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boardXOpanelLayout = new javax.swing.GroupLayout(boardXOpanel);
        boardXOpanel.setLayout(boardXOpanelLayout);
        boardXOpanelLayout.setHorizontalGroup(
            boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardXOpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardXOpanelLayout.createSequentialGroup()
                        .addComponent(area7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardXOpanelLayout.createSequentialGroup()
                        .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boardXOpanelLayout.createSequentialGroup()
                                .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(boardXOpanelLayout.createSequentialGroup()
                                .addComponent(area4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(area3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(area6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        boardXOpanelLayout.setVerticalGroup(
            boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardXOpanelLayout.createSequentialGroup()
                .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boardXOpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        XObuttonGroup.add(OrButton);
        OrButton.setText("Kółko");
        OrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrButtonActionPerformed(evt);
            }
        });

        XObuttonGroup.add(XrButton);
        XrButton.setText("Krzyżyk");
        XrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XrButtonActionPerformed(evt);
            }
        });

        newGameButton.setText("Nowa Gra");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        chooseRButtonLabel.setText("Wybierz czym zagrasz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(boardXOpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XrButton)
                    .addComponent(OrButton)
                    .addComponent(chooseRButtonLabel)
                    .addComponent(newGameButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(chooseRButtonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrButton)
                .addGap(26, 26, 26)
                .addComponent(XrButton)
                .addGap(157, 157, 157)
                .addComponent(newGameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boardXOpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrButtonActionPerformed
        playerElem = board.O;
    }//GEN-LAST:event_OrButtonActionPerformed

    private void XrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XrButtonActionPerformed
        playerElem = board.X;
    }//GEN-LAST:event_XrButtonActionPerformed

    private void area1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area1MouseClicked
       poleMouseClicked(evt, area1);
    }//GEN-LAST:event_area1MouseClicked

    private void area2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area2MouseClicked
       poleMouseClicked(evt, area2);
    }//GEN-LAST:event_area2MouseClicked

    private void area3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area3MouseClicked
       poleMouseClicked(evt, area3);
    }//GEN-LAST:event_area3MouseClicked

    private void area4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area4MouseClicked
       poleMouseClicked(evt, area4);  
    }//GEN-LAST:event_area4MouseClicked

    private void area5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area5MouseClicked
       poleMouseClicked(evt, area5);
    }//GEN-LAST:event_area5MouseClicked

    private void area6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area6MouseClicked
       poleMouseClicked(evt, area6); 
    }//GEN-LAST:event_area6MouseClicked

    private void area7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area7MouseClicked
       poleMouseClicked(evt, area7);
    }//GEN-LAST:event_area7MouseClicked

    private void area8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area8MouseClicked
       poleMouseClicked(evt, area8);
    }//GEN-LAST:event_area8MouseClicked

    private void area9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area9MouseClicked
       poleMouseClicked(evt, area9);
    }//GEN-LAST:event_area9MouseClicked

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        this.setVisible(false);
        new TicTacToeBoard().setVisible(true);
    }//GEN-LAST:event_newGameButtonActionPerformed

    
    private void poleMouseClicked(MouseEvent evt, JLabel pole){
        if (evt.getClickCount() == 2){
            if (boardsAreaList.get(pole).setTypeOfElem(playerElem)){  
                if (playerElem.equals(board.O)){
                    pole.setIcon(new ImageIcon(getClass().getResource("/TicTacToe/kolko.png")));
                    checkGameState();
                    LabelList.get(board.computersMove()).setIcon(new ImageIcon(getClass().getResource("/TicTacToe/krzyzyk.png")));
                    checkGameState();
                }
                else{
                    pole.setIcon(new ImageIcon(getClass().getResource("/TicTacToe/krzyzyk.png")));
                    checkGameState();
                    LabelList.get(board.computersMove()).setIcon(new ImageIcon(getClass().getResource("/TicTacToe/kolko.png")));
                    checkGameState();
                }        
            }        
        else 
            evt.consume();
        }
    }
    
    private void checkGameState(){
        switch (board.gameState()) {
            case 1:
                if (playerElem.equals(board.O))  {
                    JOptionPane.showMessageDialog(rootPane, "Wygrałeś ! :) ");
                    newGameButton.doClick();
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Przegrałeś ! :(" + "\n" + "Spróbuj jeszcze raz");
                    newGameButton.doClick();
                }
            case 2:
                if (playerElem.equals(board.X)){
                    JOptionPane.showMessageDialog(rootPane, "Wygrałeś ! :) ");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Przegrałeś ! :(" + "\n" + "Spróbuj jeszcze raz");
                    newGameButton.doClick();
                }
                break;
            case 3:
                JOptionPane.showMessageDialog(rootPane, "Remis");
                newGameButton.doClick();
                break;
            default:
                break;
        }
    }
    
  
   
    private void initBoardAreas(){
    LabelList.put(board.getBoardXO()[0][0], area1);
    LabelList.put(board.getBoardXO()[0][1], area2);
    LabelList.put(board.getBoardXO()[0][2], area3);
    LabelList.put(board.getBoardXO()[1][0], area4);
    LabelList.put(board.getBoardXO()[1][1], area5);
    LabelList.put(board.getBoardXO()[1][2], area6);
    LabelList.put(board.getBoardXO()[2][0], area7);
    LabelList.put(board.getBoardXO()[2][1], area8);
    LabelList.put(board.getBoardXO()[2][2], area9);
    boardsAreaList.put(area1, board.getBoardXO()[0][0]);
    boardsAreaList.put(area2, board.getBoardXO()[0][1]);
    boardsAreaList.put(area3, board.getBoardXO()[0][2]);
    boardsAreaList.put(area4, board.getBoardXO()[1][0]);
    boardsAreaList.put(area5, board.getBoardXO()[1][1]);
    boardsAreaList.put(area6, board.getBoardXO()[1][2]);
    boardsAreaList.put(area7, board.getBoardXO()[2][0]);
    boardsAreaList.put(area8, board.getBoardXO()[2][1]);
    boardsAreaList.put(area9, board.getBoardXO()[2][2]);
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boardXO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicTacToeBoard().setVisible(true);
            
        });
    }
    
    
    private final HashMap <JLabel, boardXO.polePlanszy> boardsAreaList = new HashMap <>();
    private final  HashMap < boardXO.polePlanszy, JLabel> LabelList = new HashMap <>();
    private boardXO board = new boardXO();
    private String playerElem;
    Random r = new Random();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OrButton;
    private javax.swing.ButtonGroup XObuttonGroup;
    private javax.swing.JRadioButton XrButton;
    private javax.swing.JLabel area1;
    private javax.swing.JLabel area2;
    private javax.swing.JLabel area3;
    private javax.swing.JLabel area4;
    private javax.swing.JLabel area5;
    private javax.swing.JLabel area6;
    private javax.swing.JLabel area7;
    private javax.swing.JLabel area8;
    private javax.swing.JLabel area9;
    private javax.swing.JPanel boardXOpanel;
    private javax.swing.JLabel chooseRButtonLabel;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
